# Generated by Django 3.0.4 on 2020-03-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("renting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rezerwacja",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("comment", models.TextField()),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="renting.Sala"
                    ),
                ),
            ],
        ),
    ]
